// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1chxsHq8QL9XFAwJtbfK_KPoQOF3WxxQ',
    appId: '1:1036222261989:web:0f2bf123129d98ff7b820c',
    messagingSenderId: '1036222261989',
    projectId: 'a5er-el-share3',
    authDomain: 'a5er-el-share3.firebaseapp.com',
    storageBucket: 'a5er-el-share3.firebasestorage.app',
    measurementId: 'G-5CVBT8492F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0h1GcERJdSOa7M_RCUfNHOdp66iJvpPI',
    appId: '1:1036222261989:android:834331fbc4cea1897b820c',
    messagingSenderId: '1036222261989',
    projectId: 'a5er-el-share3',
    storageBucket: 'a5er-el-share3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0PDoP_HnP1Jb3RndjRXZTn2xoGuH_oNM',
    appId: '1:1036222261989:ios:79d03023f68d51827b820c',
    messagingSenderId: '1036222261989',
    projectId: 'a5er-el-share3',
    storageBucket: 'a5er-el-share3.firebasestorage.app',
    iosBundleId: 'com.example.a5erElshare3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0PDoP_HnP1Jb3RndjRXZTn2xoGuH_oNM',
    appId: '1:1036222261989:ios:79d03023f68d51827b820c',
    messagingSenderId: '1036222261989',
    projectId: 'a5er-el-share3',
    storageBucket: 'a5er-el-share3.firebasestorage.app',
    iosBundleId: 'com.example.a5erElshare3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1chxsHq8QL9XFAwJtbfK_KPoQOF3WxxQ',
    appId: '1:1036222261989:web:2b2d04edb956ccbd7b820c',
    messagingSenderId: '1036222261989',
    projectId: 'a5er-el-share3',
    authDomain: 'a5er-el-share3.firebaseapp.com',
    storageBucket: 'a5er-el-share3.firebasestorage.app',
    measurementId: 'G-8FCE8YWKM4',
  );
}
